### PR TITLE
Rfink/init status

### PR DESCRIPTION
**Pull request by uschi2000**
This change is [Reviewable](https://reviewable.io/reviews/palantir/go-java-launcher/29)

### CODE REVIEW

**Comment by uschi2000** [comment]
128,731 lines for you, @bmoylan

**Comment by bmoylan** [comment]
looks really good!

---

Reviewed 261 of 261 files at r1, 2 of 14 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[init/cli/cli.go, line 21 at r2](https://reviewable.io:443/reviews/palantir/go-java-launcher/29#-Kd9dnzrub38Y0a3cmjv:-Kd9dnzsShLaHqphdZf2:b-3cuws9) ([raw file](https://github.com/palantir/go-java-launcher/blob/8514d182a1a248069b550b79e98397315ac9ac61/init/cli/cli.go#L21)):*
> ```Go
> )
> 
> func handleError(ctx cli.Context, err error) int {
> ```

I think I'd move this to `errors.go`

---

*[init/cli/status.go, line 50 at r1](https://reviewable.io:443/reviews/palantir/go-java-launcher/29#-Kd8_7wOKaWhxhUf60Sf:-Kd8_7wQAGPcVPuKHjIf:bq13dvx) ([raw file](https://github.com/palantir/go-java-launcher/blob/36c5ffcb66eddc74a89f5de9a312911714d40cbb/init/cli/status.go#L50)):*
> ```Go
> 	isRunning, err := lib.IsRunningByPidFile(pidfile)
> 	if err != nil {
> 		msg := fmt.Sprintf("Failed to determine wether process is running for pid-file: %s", pidfile)
> ```

sp: whether

---

*[init/lib/status.go, line 52 at r2](https://reviewable.io:443/reviews/palantir/go-java-launcher/29#-Kd9eVepc6bDlnn0nynu:-Kd9eVepc6bDlnn0nynv:b-sjbjbk) ([raw file](https://github.com/palantir/go-java-launcher/blob/8514d182a1a248069b550b79e98397315ac9ac61/init/lib/status.go#L52)):*
> ```Go
> 	}
> 
> 	if isRunning(pid) {
> ```

this is a huge nitpick, but we generally consider the outdented flow the "successful" flow. So I would do
```go
if !isRunning() {
    return 1, nil
}
return 0, nil
```
because the `return 0` path is a more successful status. Feel free to ignore :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/go-java-launcher/29#-:-Kd9fg5RhnXpvFqxtpwr:b-8d9m2o)*

**Comment by uschi2000** [comment]
Cheers, Brad. Will implement changes later today.

**Comment by uschi2000** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[init/cli/cli.go, line 21 at r2](https://reviewable.io:443/reviews/palantir/go-java-launcher/29#-Kd9dnzrub38Y0a3cmjv:-KdBqcWmmzTET3J8fiGW:b8mho7g) ([raw file](https://github.com/palantir/go-java-launcher/blob/8514d182a1a248069b550b79e98397315ac9ac61/init/cli/cli.go#L21)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

I think I'd move this to `errors.go`
</blockquote></details>

I'll leave it here since it's really core application logic rather than just error handling.

---

*[init/cli/status.go, line 50 at r1](https://reviewable.io:443/reviews/palantir/go-java-launcher/29#-Kd8_7wOKaWhxhUf60Sf:-KdBqn_mhdfBh5yu-24S:b-896fix) ([raw file](https://github.com/palantir/go-java-launcher/blob/36c5ffcb66eddc74a89f5de9a312911714d40cbb/init/cli/status.go#L50)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

sp: whether
</blockquote></details>

Done.

---

*[init/lib/status.go, line 52 at r2](https://reviewable.io:443/reviews/palantir/go-java-launcher/29#-Kd9eVepc6bDlnn0nynu:-KdBr-4MJc0uvFfi1MWI:b-896fix) ([raw file](https://github.com/palantir/go-java-launcher/blob/8514d182a1a248069b550b79e98397315ac9ac61/init/lib/status.go#L52)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

this is a huge nitpick, but we generally consider the outdented flow the "successful" flow. So I would do
```go
if !isRunning() {
    return 1, nil
}
return 0, nil
```
because the `return 0` path is a more successful status. Feel free to ignore :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/go-java-launcher/29)*

**Pull request merged**
