### PR TITLE
Upgrade godel and fix lints

### PR DESCRIPTION
**Pull request by bmoylan**
Includes #134 and #122

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/go-java-launcher/135)

### CODE REVIEW

**Comment by bmoylan** [comment]
cc @ferozco

**Comment by ferozco** [comment]
Thanks @bmoylan! Looks like the circle-template assumes go-modules. Should we also do that migration here?

**Comment by bmoylan** [comment]
We should do it, but probably in a different PR. The failing circle tasks are just about caching and they don't fail the builds. I've pushed `bm/modules` but it has some weird failure I don't see locally so have to look into that

**Comment by ferozco** [comment]
👍 cool happy to move forward with this. Thanks again!

**Pull request merged**
