### PR TITLE
Allow additional classpath args in custom configs.

### PR DESCRIPTION
**Pull request by billbindi**
This allows users to add adtional classpath args in the custom config
file in the same vein as adding additional jvmOpts.

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/go-java-launcher](https://github.com/palantir/go-java-launcher), @billbindi! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by billbindi** [comment]
@nmiyake @uschi2000 I don't know how to add reviewers, but I would like this if possible.

**Comment by uschi2000** [comment]
This library is explicitly designed around the idea of not allowing runtime changes to the classpath. This change is at odds with that idea, I think?

**Comment by billbindi** [comment]
What exactly do you mean by "runtime" changes? This will all happen at launch time, the same way the jvm options are customizable. If this is still undesired, then do you have a recommendation for swapping between multiple jars for different runs. More specifically, if I want to have a "plugin" (which is just a jar file) for my application be implemented by two completely disjoint jars, how do I set the runner to pick one over the other? Am I just supposed to modify the static config file and not the custom one?

**Comment by bmoylan** [comment]
SLS is built on the idea of immutable distributions -- trying to mutate the classpath at runtime (aka launch time, aka install time) is an antipattern that isn't going to be supported well by any of the tooling. It's also a scary vector for untrusted code execution if the deployment platform is compromised.

**Comment by billbindi** [comment]
Just to be clear, mutating the jvm args is supported (including overwriting existing ones), but adding to the classpath is not? I definitely understand that one can be more intrusive than the other, but is the distinction really that strong? I would be interested to hear of a case where the platform is compromised and not having this proposed change would mean that you are safe from an attack. Even redeploying the service (if you knew that it was compromised) won't be sufficient if there are cronjobs and other nefarious things left around by the attacker - same as if they could modify the custom file, no?

**Comment by billbindi** [comment]
Closing for now since this is not desired. I would be curious to know if there is a recommendation for the above scenario (i.e. a legitimate way of switching out jars for an SLS service), but for now we will continue to do it manually.

**Comment by billbindi** [comment]
Sorry, I would like to revisit this. It looks like in the jvmOpts you are not barred from using an arbitrary java agent. So the custom launcher is already a vulnerability if someone has access to it, no? Perhaps allowing the changing of the classpath directly is more direct, but I don't think you are really guarding against custom code execution if you allow the specification of arbitrary jvm args.

I understand the idea of the immutable distribution, and I am all for that. In my head, this feature would be used not by encouraging people to force in jars into the laid out application, but rather to add a jar from a known, absolute path (e.g. `/home/user/jars/my-custom-plugin.jar`), and the config file is what actually adds in this code. I am not sure what tooling you had in mind, but if this is still too strong of an option for that, I won't push the issue too hard, but this seems like it could be quite helpful for some services that want the ability to swap in plugins that were not around at build/distribution time.

**Comment by billbindi** [comment]
Just wanted to ping this and see if you have given any more thought to merging this? If it is really undesired I will back off, but I am not sure I fully understand the drawbacks here.

**Comment by uschi2000** [comment]
I want to maintain the separation between compile-time and runtime, and in particular the requirement to fix the class path at compile time. You're right in saying that -D arguments can be used to do whatever, but I would consider that a bug, not a feature.

Sent from Email+ secured by MobileIron

-------- Original Message --------

**Comment by billbindi** [comment]
Closing for good

**Pull request closed without merging**
